name: CI
on: [push]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    container: ghcr.io/gtk-rs/gtk4-rs/gtk4:latest

    steps:
    - uses: actions/checkout@v2
    - name: Install Rust
      run: sudo apt install rust cargo
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
